server {
    listen 80;
    root /var/www/wordpress;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTPS on;
        fastcgi_connect_timeout     60s;
        fastcgi_send_timeout        60s;
        fastcgi_read_timeout        60s;

        #fastcgi_buffers 32 32k;            # 1 MB total buffer
        #fastcgi_buffer_size 64k;          # para headers
        #fastcgi_buffers 16 16k;     # 256KB total buffer
        #fastcgi_buffer_size 32k;    # Buffer para headers
        #fastcgi_max_temp_file_size 128m;
    }

    # Rocket-Nginx configuration
    include rocket-nginx/conf.d/default.conf;

    location ~ /\.ht {
        deny all;
    }
}